spring:
  application:
    name: RateLimit-Bulkhead

resilience4j:
  ratelimiter:
    configs:
      backendApi:
        limitForPeriod: 1            # n request
        limitRefreshPeriod: 5s     # mỗi n giây
        timeoutDuration: 0ns       # Nếu hết lượt, fail ngay lập tức (không đợi)

  bulkhead:
    configs:
      backendApi:
        maxConcurrentCalls: 1        # Tối đa n request chạy song song cho mỗi IP
        maxWaitDuration: 0ns         # Nếu đầy, báo lỗi ngay (không đợi)
